[package]
name = "rustorrent"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
rand = "0.8.5"
reqwest = "0.12.4"
sha1 = "0.10.6"
tokio = {version = "1.37.0", features = ["full"]}
url = "2.5.0"
